<html>
    <head>

    </head>
    <body>
        <table>
            <tr>
                <td>
                    Bedrijfsnaam:
                </td>
                <td>
                    <?php
                        echo($_GET["companyName"]);
                    ?>
                </td>
            </tr>
            <tr>
                <td>
                    Voornaam:
                </td>
                <td>
                    <?php
                        echo($_GET["firstName"]);
                    ?>
                </td>
            </tr>
            <tr>
                <td>
                    Achternaam:
                </td>
                <td>
                    <?php
                        echo($_GET["lastName"]);
                    ?>
                </td>
            </tr>
            <tr>
                <td>
                    Telefoon:
                </td>
                <td>
                    <?php
                         echo($_GET["phoneNumber"]);
                    ?>
                </td>
            </tr>
            <tr>
                <td>
                    E-mail:
                </td>
                <td>
                    <?php
                        echo($_GET["emailAdress"]);
                    ?>
                </td>
            </tr>
            <tr>
                <td>
                    Bericht:
                </td>
                <td>
                    <?php
                        echo($_GET["message"]);
                    ?>
                </td>
            </tr>
        </table>
    </body>
</html>

